import os


def convert_to_exclude_pattern():
    a_str = '''
github.com/bangwork/bang-api/app/models/custom_language.BatchAddOrUpdateMultiLanguage
'''
    # 分行，去掉空行，每行按 . 分割，把最后一个元素替换为 *，输出
    a_list = a_str.split('\n')
    a_list = [i for i in a_list if i != '']
    a_list = [i.split('.') for i in a_list]
    a_list = [i[:-1] + ['*'] for i in a_list]
    a_list = ['.'.join(i) for i in a_list]
    # 打印
    a_list = list(set(a_list))
    for i in a_list:
        print(f"\"{i}\",")


def unique_array(a_array):
    a_array = list(set(a_array))
    # 排序
    a_array.sort()
    for i in a_array:
        print(f"\"{i}\",")


def parse_directory_path(path):
    # /Users/xhs/go/src/github.com/bangwork/bang-api-gomod/app/services/filter
    # app/services/filter
    # 按 / 分割，倒着找到第一个包含 app 的，然后取后面的
    parts = path.split("/")
    for i in range(len(parts) - 1, -1, -1):
        if "app" in parts[i]:
            return "/".join(parts[i:])


def check_model_dir():
    dir_str = '''
    activity
agent
batch
batch_refactor
card
commoncomment
component
container
dashboard
desk
field
filter
ganttchart
import_rule
importer
issuetype
kanban
layout
object
objectlink
objectlinktype
ones_task
operations
product
program
project
project_field
publishVersion
rank
related
report
role
scope_field
scope_field_config
sprint
status
tabconfig
task
version
workflow
workorder
    '''
    dir_list = dir_str.split('\n')
    dir_list = [i.strip() for i in dir_list if i != '']
    exclude_map = {}
    for dir in dir_list:
        # /Users/xhs/go/src/github.com/bangwork/bang-api-gomod/app/models/
        #     "app/services/role": PROJECT_COMMON_EXCLUDE_PATTERNS + [
        #         "github.com/bangwork/bang-api/app/models/role.*",
        #     ]
        k = f"app/services/{dir}"
        # 先校验对应的 models 目录是否存在
        models_dir = f"/Users/xhs/go/src/github.com/bangwork/bang-api-gomod/app/models/{dir}"
        if not os.path.exists(models_dir):
            print(f"models dir not exists: {models_dir}")
            continue
        # 放入 map
        exclude_map[k] = [
            f"github.com/bangwork/bang-api/app/models/{dir}.*",
        ]
    # 打印
    for k, v in exclude_map.items():
        print(f"\"{k}\": [")
        for i in v:
            print(f"    \"{i}\",")
        print("],")


def directory_module():
    a_str = '''
    app/core/objectlink
app/core/objectlink/internal
app/core/objectlink/internal/repo
app/core/product
app/core/product/relationimpl
app/core/publish_version
app/core/scope
app/core/scope/inside/domain
app/core/task
app/core/task/consumer
app/core/task/event
app/core/task/internal
app/core/task/internal/domain
app/core/task/internal/domain/property
app/core/task/internal/domain/property/driver
app/core/task/internal/domain/relation
app/core/task/internal/repo
app/core/task/utils
app/core/workflow
app/services/activity
app/services/activity/export
app/services/activity/externalactivity
app/services/activity/refactor
app/services/agent
app/services/batch
app/services/batch/add_fields
app/services/batch/attachments
app/services/batch/import_update
app/services/batch_refactor
app/services/card
app/services/card/carddelegates
app/services/card/carddelegates/performance
app/services/card/objectdelegates
app/services/common/activity
app/services/common/activity/activityimport
app/services/common/activity/related
app/services/common/field
app/services/common/field/cache
app/services/common/gantt
app/services/common/issuetype
app/services/common/objectlink
app/services/common/objectlinktype
app/services/common/report
app/services/common/status
app/services/common/task
app/services/common/template
app/services/common/template_defaultconfig
app/services/common/workorder
app/services/desk
app/services/field
app/services/ganttchart
app/services/ganttchart/refactor
app/services/importer
app/services/importer/importer_web
app/services/importer/plugin_import
app/services/importer/resolve/intermediate_file
app/services/importer/resolve/jira
app/services/importer/resolve/plugin
app/services/importer/sync
app/services/importer/sync/context
app/services/importer/sync/process
app/services/issuetype
app/services/issuetype/batch
app/services/issuetype/field_constraint
app/services/issuetype/interceptor
app/services/issuetype/trigger
app/services/kanban
app/services/layout
app/services/layout/block
app/services/layout/draft
app/services/layout/issuetype
app/services/layout/schema
app/services/layout/transform
app/services/layout/types
app/services/object
app/services/objectlink
app/services/objectlinktype
app/services/ones_task
app/services/product
app/services/program
app/services/publishVersion
app/services/publishVersion/common
app/services/scope_field
app/services/scope_field_config
app/services/status
app/services/tabconfig
app/services/task
app/services/task/common
app/services/task/executor
app/services/task/helper
app/services/task/migration
app/services/task/refactor
app/services/version
app/services/workflow
app/services/workflow/evaluators
app/services/workflow/executors
app/services/workflow/handlers
app/services/workorder
app/services_refactor/product
app/services_refactor/task
app/services_refactor/workflow_refactor/handlers
'''
    a_list = a_str.split('\n')
    a_list = [i.strip() for i in a_list if i != '']
    for i in a_list:
        #     "app/services/common/filter*": ["project", "filter"],
        print(f"\"{i}*\": [\"{i.split('/')[-1]}\", \"\"],")

def function_call():
    a_str = '''github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.AddMessages
github.com/bangwork/bang-api/app/services/commonmessage.BatchBuildMessages
github.com/bangwork/bang-api/app/services/item/delegates/utils.NewNoTxSession
github.com/bangwork/bang-api/app/models/commonmessage.AddCommonMessages
github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.BatchBuildMessages
github.com/bangwork/bang-api/app/services/item.GraphQL
github.com/bangwork/bang-api/app/services/team.GetInfo
github.com/bangwork/bang-api/app/utils.ToExcelColumn
github.com/bangwork/bang-api/app/utils.ComputeAxisForExcel
github.com/bangwork/bang-api/app/models/observer.NewUpdateTaskEvent
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerBeginLogic
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/batch/import_update.BatchImportDownload
github.com/bangwork/bang-api/app/services/common/statdog.New
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/openapi/utils/errors.Trace
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/controllers_refactor/task/plugin.HandleTaskEventPluginLogic
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerEndLogic
github.com/bangwork/bang-api/app/services_refactor/task.AddTasks
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/common.MustGetIssueTypeScope
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.TransformFields
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/queue.InterruptBatchDelete
github.com/bangwork/bang-api/app/services/queue.BatchDelete
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services_refactor/task.NewScopeIdentityFromProjectUUIDAndIssueTypeUUID
github.com/bangwork/bang-api/app/services_refactor/task.CopyTask
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/common/task.BuildXlsxComment
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/services/resource.ToXLSXBytesV2
github.com/bangwork/bang-api/app/utils.ReadLineByFileOffset
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils.FixCsvHeaderRecord
github.com/bangwork/bang-api/app/utils.FixCsvRecord
github.com/bangwork/bang-api/app/utils.ComputeAxisForExcel
github.com/bangwork/bang-api/app/utils/identity.CheckBaseUrl
github.com/bangwork/bang-api/app/services/common.MustGetTransition
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/queue.BatchMove
github.com/bangwork/bang-api/app/services/queue.InterruptBatchMove
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.GetProgressBar
github.com/bangwork/bang-api/app/services/queue.GetBatchDeleteProgressDetail
github.com/bangwork/bang-api/app/services/queue.GetBatchMoveProgressDetail
github.com/bangwork/bang-api/app/services/queue.GetBatchMoveProgressCountDetail
github.com/bangwork/bang-api/app/services/queue.GetBatchDeleteProgressCountDetail
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/field.NewFieldGroupValidateHelper
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerBeginLogic
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/common/kmutex.ImportTasksLock
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.InterruptJiraImport
github.com/bangwork/bang-api/app/services/queue.InterruptBatchDelete
github.com/bangwork/bang-api/app/services/queue.InterruptBatchMove
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/common/email.SendImportUpdateResultViaEmail
github.com/bangwork/bang-api/app/services/common/kmutex.ImportTasksLock
github.com/bangwork/bang-api/app/services/common/task.FileExists
github.com/bangwork/bang-api/app/services/common/task.BuildXlsxComment
github.com/bangwork/bang-api/app/services/common/task.GetImportErrorRecordFilePath
github.com/bangwork/bang-api/app/services/common/task.GetCheckErrorRecordFilePath
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/services/resource.HandleUploadFileAndGetFirstRow
github.com/bangwork/bang-api/app/services/resource.ToXLSXBytesV2
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils/format.ConvertXLSXToCSV
github.com/bangwork/bang-api/app/core/collector.NewCollector
github.com/bangwork/bang-api/app/models/config.GetTeamConfigByType
github.com/bangwork/bang-api/app/services/manhour/generator.NewEstimatedHourGenerator
github.com/bangwork/bang-api/app/services_refactor/task.NewScopeIdentityFromProjectUUIDAndIssueTypeUUID
github.com/bangwork/bang-api/app/services_refactor/task.ConvertFieldValues
github.com/bangwork/bang-api/app/utils.UniqueInt64Slice
github.com/bangwork/bang-api/app/utils.FixCsvHeaderRecord
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils.NewRawString
github.com/bangwork/bang-api/app/utils.FixCsvRecord
github.com/bangwork/bang-api/app/utils/format.ConvertXLSXToCSV
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/services/issuetype/batch.TargetSorter
github.com/bangwork/bang-api/app/services/issuetype/batch.EffectObjSorter
github.com/bangwork/bang-api/app/services/issuetype/batch.EffectResultSorter
github.com/bangwork/bang-api/app/services/batch.UpdateBatchExtra
github.com/bangwork/bang-api/app/services/batch.BatchTaskComplete
github.com/bangwork/bang-api/app/services/batch.BuildBatchTaskInfoPayload
github.com/bangwork/bang-api/app/services/batch.GetBatchTaskAndOneRow
github.com/bangwork/bang-api/app/services/batch.NewStatDog
github.com/bangwork/bang-api/app/services/batch.NewBatchTask
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/controllers_refactor/task/types.FromOldFieldRawValue
github.com/bangwork/bang-api/app/services/batch.BatchTaskComplete
github.com/bangwork/bang-api/app/services/batch.NewStatDog
github.com/bangwork/bang-api/app/services/batch.PushTransitTasksMessage
github.com/bangwork/bang-api/app/services/common.GetTransition
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/field.Equals
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerEndLogic
github.com/bangwork/bang-api/app/services_refactor/task.NewIncrRelatedWikiPagesParams
github.com/bangwork/bang-api/app/services_refactor/task.TransitTask
github.com/bangwork/bang-api/app/services/batch.PushUpdateIssueTypeMessage
github.com/bangwork/bang-api/app/services/batch.RandBatchTask
github.com/bangwork/bang-api/app/services/batch.HandleChangeTaskIssueEventPluginLogic
github.com/bangwork/bang-api/app/services/batch.BatchTaskComplete
github.com/bangwork/bang-api/app/services/batch.NewStatDog
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerEndLogic
github.com/bangwork/bang-api/app/services_refactor/task.ConvertFieldValues
github.com/bangwork/bang-api/app/utils/flow.If
github.com/bangwork/bang-api/app/services/batch.RandBatchTask
github.com/bangwork/bang-api/app/services/batch.HandleTaskEventPluginLogic
github.com/bangwork/bang-api/app/services/batch.BatchTaskComplete
github.com/bangwork/bang-api/app/services/batch.PushUpdateFieldValuesMessage
github.com/bangwork/bang-api/app/services/batch.NewStatDog
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerEndLogic
github.com/bangwork/bang-api/app/services_refactor/task.UpdateTasks
github.com/bangwork/bang-api/app/utils.CoerceToStringP
github.com/bangwork/bang-api/app/utils.UniqueIntSlice
github.com/bangwork/bang-api/app/models/performance.UpdatePerformanceDashboardUpdateTime
github.com/bangwork/bang-api/app/models/performance.MapSimplePerformanceDashboards
github.com/bangwork/bang-api/app/models/performance.GetPerformanceDashboard
github.com/bangwork/bang-api/app/models/report/generators.ValidateFieldUUIDs
github.com/bangwork/bang-api/app/services/sprint.MapProgressBySprint
github.com/bangwork/bang-api/app/services/sprint.SprintBurndown
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/custom_card.GetCustomCardData
github.com/bangwork/bang-api/app/services/sprint.ListUserSprintsInProjectByStatus
github.com/bangwork/bang-api/app/models/version.ListVersionsByTeamAndCategory
github.com/bangwork/bang-api/app/models/version.ListVersionsByTeam
github.com/bangwork/bang-api/app/services/task/common.GetTaskEstimateVariance
github.com/bangwork/bang-api/app/services/task/common.GetTaskTimeProgress
github.com/bangwork/bang-api/app/services/item.ItemView
github.com/bangwork/bang-api/app/models/report/generators.ValidateFieldUUIDs
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildSupersetCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildDefectEscapeDetectCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildDefectCreateSolveTrendCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildIssueAvgDurationCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildIssueRespSurvivalDurationCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildDemandDeliverySituationCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildDefectNGRateCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildManhourComparisonCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildStoryCompletedAmountCardDelegate
github.com/bangwork/bang-api/app/services/card/carddelegates/performance.BuildSprintDeliveryCardDelegate
github.com/bangwork/bang-api/app/utils/performanceutils.InitPerformanceAPIWithDefaultURL
github.com/bangwork/bang-api/app/services/card/quickquery.NewBaseQuickQuery
github.com/bangwork/bang-api/app/models/report/generators.BuildDateEndSequence
github.com/bangwork/bang-api/app/models/report/generators.TimestampToDateRange
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/layout/dynamic.IsDefaultValueListAllowedForField
github.com/bangwork/bang-api/app/services/layout/dynamic.IsCustomDefaultValueAllowedForField
github.com/bangwork/bang-api/app/services/layout/dynamic.IsDynamicDefaultValue
github.com/bangwork/bang-api/app/services/layout/dynamic.IsValidDefaultValueType
github.com/bangwork/bang-api/app/services/layout/dynamic.IsDefaultValueTypeAllowedForField
github.com/bangwork/bang-api/app/services/layout/dynamic.IsStaticDefaultValue
github.com/bangwork/bang-api/app/services/layout/dynamic.IsInheritValueType
github.com/bangwork/bang-api/app/utils.IsNull
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/issuetype/field_constraint.InvalidFields
github.com/bangwork/bang-api/app/services/issuetype/field_constraint.DeleteConstraintsByTeamUUIDWithFieldUUID
github.com/bangwork/bang-api/app/utils.ValuePtr
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/open-platform-services/field/group_field_platform.OnChange
github.com/bangwork/bang-api/app/services/open-platform-services/field/group_field_platform.Validate
github.com/bangwork/bang-api/app/services/open-platform-services/field/script_field.SearchScriptFieldOption
github.com/bangwork/bang-api/app/utils.IsEmptySlice
github.com/bangwork/bang-api/app/utils.InterfaceToString
github.com/bangwork/bang-api/app/services/common/gantt.GetPathPrefix
github.com/bangwork/bang-api/app/services/common/gantt.SortAndUpdateCommonGanttDataItems
github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.AddMessages
github.com/bangwork/bang-api/app/services/item/delegates/utils.NewNoTxSession
github.com/bangwork/bang-api/app/services/common/gantt.GetDurationByTimes
github.com/bangwork/bang-api/app/services/common/gantt.GetProgressByDoneDuration
github.com/bangwork/bang-api/app/services/common/gantt.GetPathPrefix
github.com/bangwork/bang-api/app/services/common/gantt.GetDoneDurationByProgressAndDuration
github.com/bangwork/bang-api/app/services/common/gantt.GetProgressByDoneDuration
github.com/bangwork/bang-api/app/services/common/gantt.GetDoneDurationByProgressAndDuration
github.com/bangwork/bang-api/app/services/setting.NewSession
github.com/bangwork/bang-api/app/services/setting.NewGanttChartMigration
github.com/bangwork/bang-api/app/core/scope.BatchGetScopeByUUID
github.com/bangwork/bang-api/app/models/organization.GetOrganizationWithoutStatus
github.com/bangwork/bang-api/app/utils/rabbitmq.GetMessages
github.com/bangwork/bang-api/app/utils/rabbitmq.DeleteQueue
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewImportCancel
github.com/bangwork/bang-api/app/services/importer/resolve/plugin/plugin_type/validate.ValidateFunc
github.com/bangwork/bang-api/app/services/plugin-platform/abilities.GetRealFilePath
github.com/bangwork/bang-api/app/services/plugin-platform/abilities.PathExists
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/http.CallAbilityFunction
github.com/bangwork/bang-api/app/services/importer/resolve.NewXmlScanner
github.com/bangwork/bang-api/app/services/importer/resolve.NewXmlScanner
github.com/bangwork/bang-api/app/services/importer.CheckIsStop
github.com/bangwork/bang-api/app/services/importer/resolve.NewXmlScanner
github.com/bangwork/bang-api/app/utils.StringArrayContains
github.com/bangwork/bang-api/app/utils/file.DownloadFile
github.com/bangwork/bang-api/app/models/region.IsSaas
github.com/bangwork/bang-api/app/services/importer.CheckIsStop
github.com/bangwork/bang-api/app/services/importer.GetIntermediateFileRW
github.com/bangwork/bang-api/app/models/batch.AddBatchTask
github.com/bangwork/bang-api/app/services/common/utils.BuildPasswordHash
github.com/bangwork/bang-api/app/services/importer/importer_web.HandleImportMessage
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewTeamMemberHash
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/third_import.GetThirdImportAbilitySetting
github.com/bangwork/bang-api/app/utils.CheckStrongPasswordFormat
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskJobStatusByUUID
github.com/bangwork/bang-api/app/services/importer.CheckIsStop
github.com/bangwork/bang-api/app/services/importer.BindKey
github.com/bangwork/bang-api/app/services/importer.QueueName
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewTeamMemberHash
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewJiraProgressBar
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewJiraProgressBarData
github.com/bangwork/bang-api/app/utils/metric/hubspot.SearchHubspotData
github.com/bangwork/bang-api/app/utils/metric/hubspot.UpdateHubspotData
github.com/bangwork/bang-api/app/utils/metric/segment.Identify
github.com/bangwork/bang-api/app/utils/rabbitmq.BindSampleDurableQueue
github.com/bangwork/bang-api/app/services/importer.BindKey
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/utils.GetMD5Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer.HandleNameWithProjectUUID
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/resource.UrlPathJoin
github.com/bangwork/bang-api/app/services/team.UpdateTeamWithoutCheck
github.com/bangwork/bang-api/app/services/importer.HandleName
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/models/import_rule.UpdateUserRules
github.com/bangwork/bang-api/app/models/import_rule.GetJiraUnboundUserRules
github.com/bangwork/bang-api/app/models/organization.GetOrgScale
github.com/bangwork/bang-api/app/models/organization.MapProOrganizationUserEmailByUserEmail
github.com/bangwork/bang-api/app/models/organization.GetOrganization
github.com/bangwork/bang-api/app/models/organization.ListTeamInOrganization
github.com/bangwork/bang-api/app/models/organization.GetOrgMemberCount
github.com/bangwork/bang-api/app/models/region.IsSaas
github.com/bangwork/bang-api/app/services/eventbus/user.FireUserTeamMembershipEventsByPureTeamMembers
github.com/bangwork/bang-api/app/services/import_rule.FetchUserRules
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/organization.DisableOrgMembersWithoutPermission
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/status.AddStatusConfigs
github.com/bangwork/bang-api/app/models/organization.GetOrganization
github.com/bangwork/bang-api/app/models/organization.GetOrgScale
github.com/bangwork/bang-api/app/models/organization.GetOrgMemberCount
github.com/bangwork/bang-api/app/models/usergroup.InsertOrUpdateUserGroups
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer.HandleName
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/models/permission.GetNotExistRules
github.com/bangwork/bang-api/app/models/permission.GetPermissionRuleSign
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/utils.ContainsString
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/models/permission.GetPermissionRuleSign
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/models/usergroup.BatchDeleteGroupMembers
github.com/bangwork/bang-api/app/models/usergroup.AddUserGroupMembers
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer.HandleName
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/webhook/webhook_filter.RefreshWebHookFilterIssueTypes
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/resource.FileUploadCallback
github.com/bangwork/bang-api/app/services/resource.RelateToTask
github.com/bangwork/bang-api/app/services/resource.RequestFileUpload
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout.CopyTemplate
github.com/bangwork/bang-api/app/services/layout/block.NewTab
github.com/bangwork/bang-api/app/services/layout/block.NewMetadataField
github.com/bangwork/bang-api/app/services/layout/block.UpdateBlockUUID
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer.HandleName
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/user.DoUpdateUserDepartment
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer.FixDepartmentNextId
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/constants.IsInThirdTaskLinkDetailType
github.com/bangwork/bang-api/app/services/importer/constants.IsInThirdTaskLinkType
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/status.DeleteStatusConfigImportNotCheckDefault
github.com/bangwork/bang-api/app/services/status.DeleteStatusConfig
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/sprint.UpdateSprintStatusesWithoutCheck
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/importer/constants.IsInThirdTaskLinkDetailType
github.com/bangwork/bang-api/app/services/importer/resolve.Hash
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/field.ListFieldConfigsByIssueTypeUUID
github.com/bangwork/bang-api/app/services/field.UpdateFieldConfig
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/importer/constants.IsInThirdTaskFieldType
github.com/bangwork/bang-api/app/services/importer/sync/helper.RunBatch
github.com/bangwork/bang-api/app/services/status.AddStatusConfigsWithoutCheck
github.com/bangwork/bang-api/app/models/organization.GetOrganizationWithoutStatus
github.com/bangwork/bang-api/app/models/batch.AddBatchTask
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskExtra
github.com/bangwork/bang-api/app/models/batch.BuildWaitingBatchTask
github.com/bangwork/bang-api/app/models/batch.GetLastBatchJobByJobType
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/utils/identity.CheckBaseUrl
github.com/bangwork/bang-api/app/models/batch.AddBatchTask
github.com/bangwork/bang-api/app/services/common/utils.BuildPasswordHash
github.com/bangwork/bang-api/app/services/common/utils.UpdateUserPassword
github.com/bangwork/bang-api/app/services/encryption.DecryptPasswordByRsa
github.com/bangwork/bang-api/app/services/importer.InitIntermediateFileTeamFiles
github.com/bangwork/bang-api/app/services/importer/importer_web/cache.NewTeamMemberHash
github.com/bangwork/bang-api/app/utils.CheckStrongPasswordFormat
github.com/bangwork/bang-api/app/utils/identity.CheckBaseUrl
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskJobStatusByUUID
github.com/bangwork/bang-api/app/models/migrate_notice.Model
github.com/bangwork/bang-api/app/models/organization.GetOrganizationByTeamUUID
github.com/bangwork/bang-api/app/services/common/email.SendJiraImportResultViaEmailNew
github.com/bangwork/bang-api/app/services/common/email.SendPluginImportResultViaEmail
github.com/bangwork/bang-api/app/services/common/email.SendJiraImportResultViaEmail
github.com/bangwork/bang-api/app/services/importer/sync.NewImporter
github.com/bangwork/bang-api/app/services/sso.v2/common/base.NewBaseMessage
github.com/bangwork/bang-api/app/services/sso.v2/common/base.NewBaseSendMsgReq
github.com/bangwork/bang-api/app/services/sso.v2/common/manager.ListThirdPartyTypesWithMessageAbility
github.com/bangwork/bang-api/app/services/sso.v2/common/message.SendThirdPartyMessage
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.TransformFields
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/utils.IsMissingOrNull
github.com/bangwork/bang-api/app/services/common.MustGetIssueTypeScope
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.NewIssueTypeDefaultConfigs
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common/utils.MapToArray
github.com/bangwork/bang-api/app/services/webhook/webhook_filter.RefreshWebHookFilterIssueTypes
github.com/bangwork/bang-api/app/utils.MapToArray
github.com/bangwork/bang-api/app/utils.ReverseStringMap
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout/block.AppendFieldBlock
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/issuetype/calibrator.GetConstraintCaseField
github.com/bangwork/bang-api/app/services/issuetype/field_constraint.ValidField
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/resource.MapAttachmentsDownloadURL
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRule
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRulesByIssueTypeAndProjectAndTriggerID
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRulesByIssueTypeAndTransitionAndProject
github.com/bangwork/bang-api/app/models/issuetype/trigger.DeleteRulesByProjectAndIssueType
github.com/bangwork/bang-api/app/models/issuetype/trigger.AddBatchRules
github.com/bangwork/bang-api/app/models/issuetype/trigger.DeleteRuleByUUID
github.com/bangwork/bang-api/app/models/issuetype/trigger.NewRuleRecord
github.com/bangwork/bang-api/app/models/issuetype/trigger.DeleteRulesByTransitionAndProjectAndIssueType
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRulesByTransitionAndProject
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRule
github.com/bangwork/bang-api/app/models/issuetype/trigger.GetRulesByIssueTypeAndProjectAndTriggerID
github.com/bangwork/bang-api/app/services/field.NewFieldHelper
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout/block.AppendFieldBlock
github.com/bangwork/bang-api/app/services/layout/block.AddFirstFieldBlock
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/field.NewFieldHelper
github.com/bangwork/bang-api/app/services/issuetype/calibrator.NewUnionFieldCalibrator
github.com/bangwork/bang-api/app/services/issuetype/calibrator.GetSrcFieldUUID
github.com/bangwork/bang-api/app/services/issuetype/interceptor.NewSuperAdminRules
github.com/bangwork/bang-api/app/services/issuetype/interceptor.NewFilterEmptyRules
github.com/bangwork/bang-api/app/services/scope_field.NewScopeFieldConstraintChecker
github.com/bangwork/bang-api/app/services/common.Sorted
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.NewIssueTypeDefaultConfigs
github.com/bangwork/bang-api/app/services/common.MustBrowserProjectIssueTypeScope
github.com/bangwork/bang-api/app/models/issuetype/common.GetDetailTypeByIssueTypeUUID
github.com/bangwork/bang-api/app/services/layout/schema.GetBlockAvailableChildren
github.com/bangwork/bang-api/app/services/layout/schema.GetAllQuickActions
github.com/bangwork/bang-api/app/services/layout/schema.GetTaskFields
github.com/bangwork/bang-api/app/services/layout/block.NewMetadataFields
github.com/bangwork/bang-api/app/services/layout/block.NewMetadataField
github.com/bangwork/bang-api/app/services/layout/draft.NewShaper
github.com/bangwork/bang-api/app/services/layout/dynamic.ContainsDynamicDefaultValue
github.com/bangwork/bang-api/app/services/layout/dynamic.IsDefaultValueListAllowedForField
github.com/bangwork/bang-api/app/services/layout/dynamic.IsCustomDefaultValueAllowedForField
github.com/bangwork/bang-api/app/services/layout/dynamic.IsValidDefaultValueType
github.com/bangwork/bang-api/app/services/layout/dynamic.IsDefaultValueTypeAllowedForField
github.com/bangwork/bang-api/app/services/layout/schema.FindBlocksWithFinders
github.com/bangwork/bang-api/app/models/issuetype/common.GetDetailTypeByIssueTypeUUID
github.com/bangwork/bang-api/app/services/layout/block.FindBlockByTypePrint
github.com/bangwork/bang-api/app/services/layout/transform.PackAsFormValidateEnv
github.com/bangwork/bang-api/app/services/layout/transform.FillFieldConfig
github.com/bangwork/bang-api/app/services/layout/transform.FindFields
github.com/bangwork/bang-api/app/services/layout/transform.PackAsViewValidateEnv
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/field.NewFieldGroupValidateHelper
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/layout/block.IsFieldAllowInLayoutForm
github.com/bangwork/bang-api/app/services/layout/block.IsFieldAllowInView
github.com/bangwork/bang-api/app/services/layout/schema.GetIssueTemplate
github.com/bangwork/bang-api/app/services/layout/schema.GetImportantFields
github.com/bangwork/bang-api/app/services/layout/transform.FillFieldConfig
github.com/bangwork/bang-api/app/services/layout/transform.FindFields
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/layout/transform.ConvertRecords
github.com/bangwork/bang-api/app/services/layout/block.NewQuickActionBlock
github.com/bangwork/bang-api/app/services/layout/block.IsFieldAllowInView
github.com/bangwork/bang-api/app/services/layout/block.BuildDynamicTaskFieldsBlock
github.com/bangwork/bang-api/app/services/layout/block.IsFieldAllowInClassicForm
github.com/bangwork/bang-api/app/services/layout/schema.GetLocalQuickActionUUIDsByDetailType
github.com/bangwork/bang-api/app/services/layout/schema.GetLocalImportantFields
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/layout/dynamic.IsValidDefaultValueType
github.com/bangwork/bang-api/app/services/layout/dynamic.IsInheritValueType
github.com/bangwork/bang-api/app/services/layout/schema.FindBlocksWithFinders
github.com/bangwork/bang-api/app/services/layout/transform.PackAsFormValidateEnv
github.com/bangwork/bang-api/app/services/layout/transform.PackAsViewValidateEnv
github.com/bangwork/bang-api/app/services/layout/transform.CheckSumBlocks
github.com/bangwork/bang-api/app/services/layout/transform.TreeToRecord
github.com/bangwork/bang-api/app/services/tabconfig.GetDefaultConfig
github.com/bangwork/bang-api/app/services/layout/schema.GetImportantFields
github.com/bangwork/bang-api/app/services/layout/transform.BuildDefaultFieldConfigPayload
github.com/bangwork/bang-api/app/services/tabconfig.CombineIssueTypeDefaultTabConfigs
github.com/bangwork/bang-api/app/services/layout/redis.GetLayoutStamp
github.com/bangwork/bang-api/app/services/layout/transform.AddCardFilter
github.com/bangwork/bang-api/app/services/layout/transform.ReplaceCardFilter
github.com/bangwork/bang-api/app/services/layout/transform.BuildFieldConfigPayload
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/layout/schema.FindBlocksWithFinders
github.com/bangwork/bang-api/app/services/layout/transform.PackAsFormValidateEnv
github.com/bangwork/bang-api/app/services/layout/transform.TreeToRecord
github.com/bangwork/bang-api/app/services/layout/transform.DiffBlocks
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/layout/block.CheckIsThirdQuickActionID
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/layout/block.NewBlock
github.com/bangwork/bang-api/app/services/layout/block.NewPluginCard
github.com/bangwork/bang-api/app/services/layout/block.NewBlock
github.com/bangwork/bang-api/app/utils.StringStructSetToArray
github.com/bangwork/bang-api/app/services/task/common.BuildLinksMessage
github.com/bangwork/bang-api/app/services/common/objectlink.AddObjectLink
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/services/common/objectlinktype.LoadList
github.com/bangwork/bang-api/app/models/usergroup.GetGroupsMemberCountIgnoreUserRoleByProject
github.com/bangwork/bang-api/app/models/usergroup.GetGroupsMemberCountIgnoreUserRoleByProgram
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/services/publishVersion/common.BatchUpdatePublishVersion
github.com/bangwork/bang-api/app/utils.CompareStrings
github.com/bangwork/bang-api/app/utils.UniqueNoNullSliceAndRemove
github.com/bangwork/bang-api/app/utils.ContainsString
github.com/bangwork/bang-api/app/models/permission.DeleteRulesByContextAndDomain
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/field.DeleteImportantField
github.com/bangwork/bang-api/app/services/field.GetConfig
github.com/bangwork/bang-api/app/services/field.NewFieldHelper
github.com/bangwork/bang-api/app/services/field.NewFieldConfigPayload
github.com/bangwork/bang-api/app/services/field.DeleteImportantListField
github.com/bangwork/bang-api/app/services/layout.GetDraft
github.com/bangwork/bang-api/app/services/layout.PublishDraft
github.com/bangwork/bang-api/app/services/layout.SaveDraft
github.com/bangwork/bang-api/app/services/layout/block.AppendFieldBlock
github.com/bangwork/bang-api/app/services/layout/block.RemoveFieldBlock
github.com/bangwork/bang-api/app/services/layout/transform.ConvertTree
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/models/observer.NewUpdateSprintEvent
github.com/bangwork/bang-api/app/models/observer.NewUpdateProjectEvent
github.com/bangwork/bang-api/app/models/observer.NewUpdateProductEvent
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/field.DoDeleteField
github.com/bangwork/bang-api/app/services/common.MustGetIssueTypeScope
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/models/objectcount.AddOrUpdateObjectCount
github.com/bangwork/bang-api/app/models/observer.NewAddTaskEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.AncestorUUIDs
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewAddBatchTaskEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.GetIssueTypeUUID
github.com/bangwork/bang-api/app/services/automation/trigger/task.IsRootTask
github.com/bangwork/bang-api/app/services/automation/trigger/task.HandleIssueTypeBeforeReturning
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/objectlink.AddObjectLink
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/resource.BatchPersistentDocument
github.com/bangwork/bang-api/app/services/resource.ConfigForTypeLabel
github.com/bangwork/bang-api/app/services/resource.BatchIndexDocument
github.com/bangwork/bang-api/app/services/task/helper.UpdateTaskFieldValues
github.com/bangwork/bang-api/app/services/task/helper.AddRelatedProducts
github.com/bangwork/bang-api/app/services/task/helper.AddTaskMainContainerRelation
github.com/bangwork/bang-api/app/services/task/helper.NewDefaultCheckPermissionHelper
github.com/bangwork/bang-api/app/utils/mime.IsTIFF
github.com/bangwork/bang-api/app/utils/mime.IsDocumentMIME
github.com/bangwork/bang-api/app/utils/mime.IsPSD
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/models/objectcount.AddOrUpdateObjectCount
github.com/bangwork/bang-api/app/models/observer.NewUpdateSprintEvent
github.com/bangwork/bang-api/app/models/observer.NewUpdateProjectEvent
github.com/bangwork/bang-api/app/models/observer.NewUpdateTaskEvent
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/publishVersion/common.ClearPublishVersion
github.com/bangwork/bang-api/app/services/task/common.BuildProgressFieldValue
github.com/bangwork/bang-api/app/utils.IsValidTaskUUID
github.com/bangwork/bang-api/app/utils/rabbitmq.ExpirationSecond
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/services/field.NewFieldValueFromFieldRawValue
github.com/bangwork/bang-api/app/utils.GetDayHourMinuteByDuration
github.com/bangwork/bang-api/app/utils.IsValidTaskUUID
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewTaskFieldValueChangedEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewTaskAssignedEvent
github.com/bangwork/bang-api/app/utils.CheckWikiPages
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskJobStatusAndUnprocessedCountByUUID
github.com/bangwork/bang-api/app/models/batch.AddBatchTask
github.com/bangwork/bang-api/app/models/batch.GetBatchJobByUUID
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskStatus
github.com/bangwork/bang-api/app/services/common/kmutex.ImportTasksLock
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/utils.ReadNextLineByOffset
github.com/bangwork/bang-api/app/utils.CountCsvFileRecordsByFilter
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils.FixCsvHeaderRecord
github.com/bangwork/bang-api/app/utils.FixCsvRecord
github.com/bangwork/bang-api/app/utils/format.ConvertXLSXToCSV
github.com/bangwork/bang-api/app/utils/rabbitmq.BindSampleDurableQueue
github.com/bangwork/bang-api/app/models/notice.SendRelatedTasksEmail
github.com/bangwork/bang-api/app/models/notice.AddTaskNotice
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewTaskLinkedEvent
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/thirdparty.SendMergedThirdPartyMsg
github.com/bangwork/bang-api/app/services/smsconfig.SendRelatedNoticeShortMessage
github.com/bangwork/bang-api/app/services/task/common.BuildLinksMessage
github.com/bangwork/bang-api/app/services/task/common.BuildLinkUpdateMessage
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskCounts
github.com/bangwork/bang-api/app/models/batch.AddBatchTaskRecord
github.com/bangwork/bang-api/app/models/batch.GetBatchJob
github.com/bangwork/bang-api/app/models/objectcount.AddOrUpdateObjectCount
github.com/bangwork/bang-api/app/models/observer.NewAddTaskEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.GetIssueTypeUUID
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewAddBatchTaskEvent
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/kmutex.ImportTasksLock
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/field.ValidateTaskPlanStartDateAndPlanEndDate
github.com/bangwork/bang-api/app/services/field.MapIssueTypeUUIDByLayoutUUID
github.com/bangwork/bang-api/app/services/field.QueryTaskUUIDsByRequirement
github.com/bangwork/bang-api/app/services/mail.PublishEmailMessageToMQ
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/utils.FixCsvRecords
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/services/resource.HandleUploadFileAndGetFirstRow
github.com/bangwork/bang-api/app/services/common/objectlinktype.CheckLinkType
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/models/pipeline.ListTasksCommits
github.com/bangwork/bang-api/app/models/pipeline.MapRunsByCommitHashes
github.com/bangwork/bang-api/app/models/publishVersion.MapPublishVersionByTaskUUIDs
github.com/bangwork/bang-api/app/models/publishVersion.MapVersionNameByUUIDs
github.com/bangwork/bang-api/app/models/publishVersion.MapContentsByPublishVersions
github.com/bangwork/bang-api/app/services/common.MustGetIssueTypeScope
github.com/bangwork/bang-api/app/services/common/objectlinktype.CheckLinkType
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/services/config.GetOrgCommonConfig
github.com/bangwork/bang-api/app/services/config.GetBotUserMap
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/services/field.NewFieldHelper
github.com/bangwork/bang-api/app/services/field.NewFieldValueFromFieldRawValue
github.com/bangwork/bang-api/app/services/field.BuildSystemFieldValues
github.com/bangwork/bang-api/app/services/field.NewFieldRawValueFromValue
github.com/bangwork/bang-api/app/services/pipeline.NewRunPayload
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/user_list_filter.CallUserListFilterFunc
github.com/bangwork/bang-api/app/services/project/archive.CheckMangerProjectPermission
github.com/bangwork/bang-api/app/services/task/common.GetTaskEstimateVariance
github.com/bangwork/bang-api/app/services/task/common.GetTaskTimeProgress
github.com/bangwork/bang-api/app/services/testcase.RelatedTestCasePayloadSorter
github.com/bangwork/bang-api/app/services/testcase.RelatedPlanTestCasePayloadSorter
github.com/bangwork/bang-api/app/services/testcase.NewRelatedTestCasePayload
github.com/bangwork/bang-api/app/services/testcase.NewRelatedTestCasePlanPayload
github.com/bangwork/bang-api/app/services/testcase.NewRelatedPlanTestCasePayload
github.com/bangwork/bang-api/app/services/testcase.RelatedTestCasePlanPayloadSorter
github.com/bangwork/bang-api/app/utils.Md2Html
github.com/bangwork/bang-api/app/utils.IsUUID
github.com/bangwork/bang-api/app/utils.CompareStrings
github.com/bangwork/bang-api/app/utils.CompareStringsOrderly
github.com/bangwork/bang-api/app/models/observer.NewUpdateSprintEvent
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/utils.HasIllegalAscii
github.com/bangwork/bang-api/app/utils.HasCharacter
github.com/bangwork/bang-api/app/services/publishVersion/common.BatchUpdatePublishVersion
github.com/bangwork/bang-api/app/services/common/task.LoadSprintNamesInProject
github.com/bangwork/bang-api/app/services/common/task.BuildProductFieldDesc
github.com/bangwork/bang-api/app/services/common/task.BuildRequiredFieldDesc
github.com/bangwork/bang-api/app/services/common/task.BuildDescRequiredOptionDesc
github.com/bangwork/bang-api/app/services/common/task.BuildOnlyRequiredDesc
github.com/bangwork/bang-api/app/services/common/task.SplitIssueTypeNames
github.com/bangwork/bang-api/app/services/common/task.BuildDescRequiredFieldDescOptionDesc
github.com/bangwork/bang-api/app/services/common/task.LoadFieldOptions
github.com/bangwork/bang-api/app/services/common/task.LoadDepartmentNames
github.com/bangwork/bang-api/app/services/common/task.GetIssueTypeMap
github.com/bangwork/bang-api/app/services/common/task.LoadProjectNames
github.com/bangwork/bang-api/app/services/common/task.BuildOptionsDesc
github.com/bangwork/bang-api/app/services/common/task.CombineMultiDesc
github.com/bangwork/bang-api/app/services/common/task.LoadProductNames
github.com/bangwork/bang-api/app/services/common/task.BuildDescRequiredFieldDesc
github.com/bangwork/bang-api/app/services/resource.ToCSVBytes
github.com/bangwork/bang-api/app/services/resource.ToXLSXBytesV2
github.com/bangwork/bang-api/app/utils.StringArrayUnion
github.com/bangwork/bang-api/app/utils.ToExcelColumn
github.com/bangwork/bang-api/app/utils.ComputeAxisForExcel
github.com/bangwork/bang-api/app/services/config.IsManhourSimpleMode
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/manhour/generator.NewEstimatedHourGenerator
github.com/bangwork/bang-api/app/services/task/executor.Commit
github.com/bangwork/bang-api/app/services/task/executor.GetAddManhours
github.com/bangwork/bang-api/app/services/task/executor.AsyncSuccessCallback
github.com/bangwork/bang-api/app/services/task/executor.GetAnyToStatusTransition
github.com/bangwork/bang-api/app/services/task/executor.SuccessCallback
github.com/bangwork/bang-api/app/services/task/executor.NewUpdateAnyStatusExecutor
github.com/bangwork/bang-api/app/services/task/executor.ValidateAndPrepare
github.com/bangwork/bang-api/app/services/task/executor.ValidateAndPrepareInStream
github.com/bangwork/bang-api/app/services/common.MustGetTaskMainContainer
github.com/bangwork/bang-api/app/services/field.BuildFieldValueByFieldAndValue
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/models/observer.NewUpdateTaskEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewTaskStatusTransitedEvent
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/core/scope.BatchGetScopeByUUID
github.com/bangwork/bang-api/app/services/automation/types.NewDynamicTextFieldValuesFetcher
github.com/bangwork/bang-api/app/services/automation/types.NewNilItemField
github.com/bangwork/bang-api/app/services/automation/types.GetDefaultDateRawFormatter
github.com/bangwork/bang-api/app/services/automation/types.ChangeLogToExtra
github.com/bangwork/bang-api/app/services/automation/types.NewItemFieldValue
github.com/bangwork/bang-api/app/services/automation/types.StringChangeLog
github.com/bangwork/bang-api/app/services/automation/types.NewAliasEvaluator
github.com/bangwork/bang-api/app/services/automation/types.NewNormalFieldValuesFetcher
github.com/bangwork/bang-api/app/services/automation/types.GetDefaultTimeRawFormatter
github.com/bangwork/bang-api/app/services/automation/types.GetDefaultIntegerToStringRawFormatter
github.com/bangwork/bang-api/app/services/automation/types.NewAliasEvalUnit
github.com/bangwork/bang-api/app/services/automation/types.GetDefaultFloatToStringRawFormatter
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services_refactor/task.ConvertFieldValues
github.com/bangwork/bang-api/app/services_refactor/task.CheckFieldConstraints
github.com/bangwork/bang-api/app/utils.NewCallbackList
github.com/bangwork/bang-api/app/utils.CoerceToStringP
github.com/bangwork/bang-api/app/core/objectlink/types.BuildTaskFieldUUID
github.com/bangwork/bang-api/app/services/automation/types.StringChangeLog
github.com/bangwork/bang-api/app/services/automation/types.LinkDescToObjectLinkedDesc
github.com/bangwork/bang-api/app/services/automation/types.IFaceVarsToCamundaVars
github.com/bangwork/bang-api/app/services/automation/types.NewNormalFieldValuesFetcher
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services_refactor/task.ConvertFieldValues
github.com/bangwork/bang-api/app/services_refactor/task.CheckConstraintsAndFillDefaultValue
github.com/bangwork/bang-api/app/services_refactor/task.NewScopeIdentityFromProjectUUIDAndIssueTypeUUID
github.com/bangwork/bang-api/app/utils.CoerceToString
github.com/bangwork/bang-api/app/services/eventbus/types.NewEventContext
github.com/bangwork/bang-api/app/services/related.NewVersion
github.com/bangwork/bang-api/app/services/related.NewHelper
github.com/bangwork/bang-api/app/services/related.NewProduct
github.com/bangwork/bang-api/app/services/related.NewVersion
github.com/bangwork/bang-api/app/services/related.NewHelper
github.com/bangwork/bang-api/app/services/related.NewProduct
github.com/bangwork/bang-api/app/services/related.NewVersion
github.com/bangwork/bang-api/app/services/related.NewHelper
github.com/bangwork/bang-api/app/services/related.NewVersions
github.com/bangwork/bang-api/app/services/related.NewHelper
github.com/bangwork/bang-api/app/services/related.NewVersion
github.com/bangwork/bang-api/app/services/related.NewHelper
github.com/bangwork/bang-api/app/services/related.NewProducts
github.com/bangwork/bang-api/app/services/common.GetTransition
github.com/bangwork/bang-api/app/services/common/utils.NewValueFixer
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerBeginLogic
github.com/bangwork/bang-api/app/services/plugin-platform/abilities/implement/task_event_handler.TaskEventHandlerEndLogic
github.com/bangwork/bang-api/app/utils.StringArrayContains
github.com/bangwork/bang-api/app/utils.NewValueFixer
github.com/bangwork/bang-api/app/utils.InterfaceToString
github.com/bangwork/bang-api/app/models/condition.IsEmpty
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.TransformFields
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildDefaultTransitionRawFields
github.com/bangwork/bang-api/app/utils.IsUUID
github.com/bangwork/bang-api/app/utils.IsMissingOrNull
github.com/bangwork/bang-api/app/services/common.MustGetIssueTypeScope
github.com/bangwork/bang-api/app/services/common.MustBrowserProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/common.MustGetTaskMainContainer
github.com/bangwork/bang-api/app/services/common.MustBrowserIssueTypeScope
github.com/bangwork/bang-api/app/services/common.MustGetTask
github.com/bangwork/bang-api/app/services/common.MustManageProjectIssueTypeScope
github.com/bangwork/bang-api/app/services/common.MustGetTransition
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.TransformFields
github.com/bangwork/bang-api/app/services/common/utils.MapToArray
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/utils.MapToArray
github.com/bangwork/bang-api/app/utils.IsMissingOrNull
github.com/bangwork/bang-api/app/services/common.MustGetTaskMainContainer
github.com/bangwork/bang-api/app/models/action.NewActionHub
github.com/bangwork/bang-api/app/models/condition.NewEvaluatorHub
github.com/bangwork/bang-api/app/models/observer.NewUpdateTaskEvent
github.com/bangwork/bang-api/app/services/automation/trigger/task.NewTaskStatusTransitedEvent
github.com/bangwork/bang-api/app/services/common.MustGetTaskMainContainer
github.com/bangwork/bang-api/app/services/common/automation.GetGateway
github.com/bangwork/bang-api/app/services/common/observer.PutEvent
github.com/bangwork/bang-api/app/services/workflow/executors.NewSimpleExecutor
github.com/bangwork/bang-api/app/services/config.IsManhourSimpleMode
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/models/action.Error
github.com/bangwork/bang-api/app/models/action.Done
github.com/bangwork/bang-api/app/services/notify.IsValidNoticeMethodFormat
github.com/bangwork/bang-api/app/services/resource.RequestFileUpload
github.com/bangwork/bang-api/app/services/resource.GetInternalAttachment
github.com/bangwork/bang-api/app/services/task/helper.NewPassingPermissionHelper
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/utils.EllipsizeString
github.com/bangwork/bang-api/app/services/resource.GetInternalAttachment
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/utils.ExtractHtmlElements
github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.AddMessages
github.com/bangwork/bang-api/app/services/commonmessage.BatchBuildMessages
github.com/bangwork/bang-api/app/services/ganttchart.AddTaskGanttDataRefreshParentData
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithMultipleExecutor
github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.AddMessages
github.com/bangwork/bang-api/app/services/commonmessage.BatchBuildMessages
github.com/bangwork/bang-api/app/services/commonmessage.NewItemMessageHandler
github.com/bangwork/bang-api/app/services/commonmessage.AddMessages
github.com/bangwork/bang-api/app/services/commonmessage.BatchBuildMessages
github.com/bangwork/bang-api/app/services/ganttchart.AddTaskGanttDataRefreshParentData
github.com/bangwork/bang-api/app/services/common/task.LoadSprintNamesInProject
github.com/bangwork/bang-api/app/services/common/task.LoadDepartmentNames
github.com/bangwork/bang-api/app/services/common/task.GetIssueTypeMap
github.com/bangwork/bang-api/app/services/common/task.LoadFieldOptions
github.com/bangwork/bang-api/app/services/common/task.LoadProjectNames
github.com/bangwork/bang-api/app/services/resource.ToXLSXBytesV2
github.com/bangwork/bang-api/app/utils.ToExcelColumn
github.com/bangwork/bang-api/app/utils.ComputeAxisForExcel
github.com/bangwork/bang-api/app/utils/oldtimetransfer.ParserTimeStr
github.com/bangwork/bang-api/app/utils/oldtimetransfer.ParserTimeStr
github.com/bangwork/bang-api/app/services/common/email.SendImportActivitiesCanceledEmail
github.com/bangwork/bang-api/app/services/common/email.SendImportActivitiesResultViaEmail
github.com/bangwork/bang-api/app/services/common/task.BuildXlsxCommentWithUDF
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/utils.ReadLinesByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/services/resource.HandleUploadFileAndGetFirstRow
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskCounts
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskStatus
github.com/bangwork/bang-api/app/services/common/task.TranslateIfIsPlaceholder
github.com/bangwork/bang-api/app/utils.CountCsvFileRecordsByFilter
github.com/bangwork/bang-api/app/utils.ReadLineByCSVFileOffsetByFilter
github.com/bangwork/bang-api/app/utils.FixCsvHeaderRecord
github.com/bangwork/bang-api/app/utils.FixCsvRecord
github.com/bangwork/bang-api/app/utils/format.ConvertXLSXToCSVNewFile
github.com/bangwork/bang-api/app/models/batch.AddBatchTask
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskStatus
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/utils/queue.NewJobId
github.com/bangwork/bang-api/app/utils/rabbitmq.BindSampleDurableQueue
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskCounts
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskExtra
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskStatus
github.com/bangwork/bang-api/app/models/batch.GetBatchJobWithExtraByUUID
github.com/bangwork/bang-api/app/models/batch.UpdateBatchTaskStatus
github.com/bangwork/bang-api/app/utils/rabbitmq.ExpirationSecond
github.com/bangwork/bang-api/app/utils/rabbitmq.NoExpiration
github.com/bangwork/bang-api/app/utils/rabbitmq.PublishSampleDurableMessage
github.com/bangwork/bang-api/app/models/permission.MapDomainCodeByContext
github.com/bangwork/bang-api/app/services/common.Sorted
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/services/task/common.BuildLinksMessage
github.com/bangwork/bang-api/app/services/resource.GetFilePath
github.com/bangwork/bang-api/app/services/common/utils.MapToArray
github.com/bangwork/bang-api/app/services/common/utils.NewValueFixer
github.com/bangwork/bang-api/app/utils.CompareStrings
github.com/bangwork/bang-api/app/services/notify.IsValidNoticeMethodFormat
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.NewIssueTypeDefaultConfigs
github.com/bangwork/bang-api/app/utils.RandomColor
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.ReadViewIssueTypeTemplate
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.NewIssueTypeDefaultConfigs
github.com/bangwork/bang-api/app/services/common/template_defaultconfig.BuildIssueTypeDefaultConfigsFromJson
github.com/bangwork/bang-api/app/utils.StringStructSetToArray
github.com/bangwork/bang-api/app/services_refactor/task.RegisterReplaceRelationConverter
github.com/bangwork/bang-api/app/core/collector.NewCollector
github.com/bangwork/bang-api/app/core/objectlink/types.BuildTaskFieldUUID
github.com/bangwork/bang-api/app/core/scope.GetDefaultValuesFromLayout
github.com/bangwork/bang-api/app/core/task/utils.GetTaskDomains
github.com/bangwork/bang-api/app/services/field.NewFieldGroupValidateHelper
github.com/bangwork/bang-api/app/core/scope.LayoutCheckFields
github.com/bangwork/bang-api/app/services/config.IsManhourSimpleMode
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/field.NewFieldGroupValidateHelper
github.com/bangwork/bang-api/app/services/manhour/generator.NewEstimatedHourGenerator
github.com/bangwork/bang-api/app/utils.CoerceToStringP
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/services/task/executor.NewCopyRelatedTask
github.com/bangwork/bang-api/app/services/task/executor.NewUpdateDefectStatusDirectExecutor
github.com/bangwork/bang-api/app/services/task/executor.NewCopyTaskWatchersExecutor
github.com/bangwork/bang-api/app/services/task/executor.NewCopyTaskTest
github.com/bangwork/bang-api/app/services/task/executor.NewCreateDemandByDefectMessagesExecutor
github.com/bangwork/bang-api/app/services/task/executor.NewCopyTaskResourcesExecutor
github.com/bangwork/bang-api/app/services/task/executor.NewMergeDefectMessagesExecutor
github.com/bangwork/bang-api/app/services/task/executor.NewCopyRelatedWiki
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithMultipleExecutor
github.com/bangwork/bang-api/app/core/objectlink/types.BuildTaskFieldUUID
github.com/bangwork/bang-api/app/utils/user.GetBotUserByTeam
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/utils.CoerceToStringP
github.com/bangwork/bang-api/app/utils.CoerceToString
github.com/bangwork/bang-api/app/utils.TrimStringPointer
github.com/bangwork/bang-api/app/models/publishVersion.MapContentsByPublishVersions
github.com/bangwork/bang-api/app/utils.CompareStrings
github.com/bangwork/bang-api/app/core/scope.GetScopeByProjectUUIDAndIssueTypeUUID
github.com/bangwork/bang-api/app/services/field.NewFieldHelper
github.com/bangwork/bang-api/app/services/workflow/handlers.GetValueBySpecialField
github.com/bangwork/bang-api/app/services/workflow/handlers.GetFieldValueByValueTypeAndFieldUUID
github.com/bangwork/bang-api/app/services_refactor/task.UpdateTasksWithHeavyResponse
github.com/bangwork/bang-api/app/utils.CoerceToStringP
github.com/bangwork/bang-api/app/utils.InterfaceToString
github.com/bangwork/bang-api/app/models/action.Error
github.com/bangwork/bang-api/app/models/action.Done
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/services/task/executor.GetAnyToStatusTransition
github.com/bangwork/bang-api/app/utils.StringStructSetToArray
github.com/bangwork/bang-api/app/core/objectlink/types.BuildTaskFieldUUID
github.com/bangwork/bang-api/app/core/task/types.RegisterRelationFactory
github.com/bangwork/bang-api/app/core/objectlink/types.BuildTaskFieldUUID
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.RelationValueToUUIDs
github.com/bangwork/bang-api/app/core/task/utils.GetTaskDomains
github.com/bangwork/bang-api/app/services/common/objectlinktype.CheckLinkTypeWithGivenCondition
github.com/bangwork/bang-api/app/services/common/objectlinktype.ListByUUIDs
github.com/bangwork/bang-api/app/utils/audit_log.SendTeamAuditLog
github.com/bangwork/bang-api/app/core/task/types.RegisterRelationFactory
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.GetRelationValueUUIDs
github.com/bangwork/bang-api/app/core/task/types.TaskKeysToTaskUUIDs
github.com/bangwork/bang-api/app/core/task/types.RelationValueToUUIDs
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.RelationValueToUUIDs
github.com/bangwork/bang-api/app/core/task/types.TaskKeysToTaskUUIDs
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/services/publishVersion/common.ClearPublishVersion
github.com/bangwork/bang-api/app/core/issuetype.GetIssueTypeWithoutTranslation
github.com/bangwork/bang-api/app/services/publishVersion/common.ClearPublishVersion
github.com/bangwork/bang-api/app/core/collector.AppendTeamUUIDAheadKey
github.com/bangwork/bang-api/app/core/issuetype.MapIssueTypeRecordByUUID
github.com/bangwork/bang-api/app/core/project.MapProjectRecordByUUID
github.com/bangwork/bang-api/app/core/scope/inside/domain.ScopeRecordToDomain
github.com/bangwork/bang-api/app/core/scope/inside/domain.ReadScopeDomainFromDB
github.com/bangwork/bang-api/app/core/scope/inside/domain.BatchReadLayoutDomainFromDB
github.com/bangwork/bang-api/app/core/scope/inside/domain.BatchReadScopeLayoutDomainFromDB
github.com/bangwork/bang-api/app/core/scope/inside/domain.BatchReadScopeDomainFromDB
github.com/bangwork/bang-api/app/core/task/types.IsCustomField
github.com/bangwork/bang-api/app/services/config.IsManhourSimpleMode
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/services/field.FixFieldConfigsDefaultValue
github.com/bangwork/bang-api/app/utils.IsNil
github.com/bangwork/bang-api/app/core/task/internal/domain.BatchReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.NewReadOnlyTask
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/types.NewTaskKeys
github.com/bangwork/bang-api/app/core/task/utils.GetTaskDomains
github.com/bangwork/bang-api/app/utils/user.GetBotUserByTeam
github.com/bangwork/bang-api/app/core/collector.AppendTeamUUIDAheadKey
github.com/bangwork/bang-api/app/core/collector.NewCollector
github.com/bangwork/bang-api/app/core/scope.GetScopeDefaultStatusUUID
github.com/bangwork/bang-api/app/core/task/internal/domain.MapReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.NewAssignSetter
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildRelationsForNewTask
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildProperties
github.com/bangwork/bang-api/app/core/task/internal/domain.CheckLicenseInBatch
github.com/bangwork/bang-api/app/core/task/internal/domain.PreloadParent
github.com/bangwork/bang-api/app/core/task/internal/domain.InvalidateWatchersCache
github.com/bangwork/bang-api/app/core/task/internal/domain.NewScratchTaskBuilder
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildRelations
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildProperties
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/types.GetRelationValueUUIDs
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildRelations
github.com/bangwork/bang-api/app/core/task/internal/domain.NewTransitionStub
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildProperties
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.NewDiscussionDomain
github.com/bangwork/bang-api/app/services/workflow/executors.DoServiceWithSingleExecutor
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/services/common.MustGetTaskMainContainer
github.com/bangwork/bang-api/app/core/scope.MustGetScopeByUUID
github.com/bangwork/bang-api/app/core/task/internal/domain.NewAssignSetter
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildRelationsForNewTask
github.com/bangwork/bang-api/app/core/task/internal/domain.CheckLicenseInBatch
github.com/bangwork/bang-api/app/core/task/internal/domain.PreloadParent
github.com/bangwork/bang-api/app/core/task/internal/domain.NewProjectStub
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.NewScratchTaskBuilder
github.com/bangwork/bang-api/app/core/task/types.GetRelationDrivers
github.com/bangwork/bang-api/app/core/task/types.GetPropertyDrivers
github.com/bangwork/bang-api/app/services/config.IsManhourSimpleMode
github.com/bangwork/bang-api/app/services/config.GetManhourMode
github.com/bangwork/bang-api/app/services/project/archive.CheckMangerProjectPermission
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.MapTaskPaths
github.com/bangwork/bang-api/app/core/scope.GetScopeByProjectUUIDAndIssueTypeUUID
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildRelations
github.com/bangwork/bang-api/app/core/task/internal/domain.GetScopeIsSub
github.com/bangwork/bang-api/app/core/task/internal/domain.BuildProperties
github.com/bangwork/bang-api/app/core/task/internal/domain.NewScopeStub
github.com/bangwork/bang-api/app/core/task/internal/domain.ReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.RegisterFieldTypeRelationTypeMapping
github.com/bangwork/bang-api/app/core/task/internal/domain.RegisterFieldTypePropertyTypeMapping
github.com/bangwork/bang-api/app/core/task/internal/domain.RegisterFieldUUIDRelationTypeMapping
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewSprintPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewPlanEndDatePropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewScriptFieldTypeMultiOptionPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewProgressPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewTextSingleLineFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewTimePropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewIntegerPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewDatePropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewTextMultipleLinesFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewInternalProgressPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewScriptFieldTypeOptionPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewPlanStartDatePropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/property.NewFloatPropertyFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewUserRelationFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewMultiOptionFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewSingleOptionFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewUserListRelationFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewDepartmentListRelationFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewWatcherRelationFactory
github.com/bangwork/bang-api/app/core/task/internal/domain/relation.NewMultiOptionFactory
github.com/bangwork/bang-api/app/core/task/types.RegisterPropertyFactory
github.com/bangwork/bang-api/app/core/task/types.RegisterRelationFactory
github.com/bangwork/bang-api/app/core/task/internal/repo.NewContainerRepositoryImpl
github.com/bangwork/bang-api/app/core/task/internal/repo.NewStatusRepository
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldOptionRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.NewTaskRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldMultiValueRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.NewScriptFieldOptionRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldValueRepo
github.com/bangwork/bang-api/app/core/collector.AppendTeamUUIDAheadKey
github.com/bangwork/bang-api/app/core/collector.AppendTeamUUIDAheadKey
github.com/bangwork/bang-api/app/core/task/event.FireTaskStatusChangedEvent
github.com/bangwork/bang-api/app/core/task/event.FireTaskScopeChangedEvent
github.com/bangwork/bang-api/app/core/task/event.FireTaskCreatedEvent
github.com/bangwork/bang-api/app/core/task/event.FireTaskUpdatedEvent
github.com/bangwork/bang-api/app/core/task/event.FireTaskDeletedEvent
github.com/bangwork/bang-api/app/core/task/types.GetPropertyDrivers
github.com/bangwork/bang-api/app/core/task/types.GetRelationDrivers
github.com/bangwork/bang-api/app/core/utils/di.NewContainer
github.com/bangwork/bang-api/app/services/project/archive.CheckMangerProjectPermission
github.com/bangwork/bang-api/app/utils.IsEqualStringPointer
github.com/bangwork/bang-api/app/utils/numbers.GenerateNumbers
github.com/bangwork/bang-api/app/core/issuetype.GetIssueTypeWithoutTranslation
github.com/bangwork/bang-api/app/core/project.GetProjectByUUID
github.com/bangwork/bang-api/app/core/task/types.GetPropertyFactory
github.com/bangwork/bang-api/app/core/task/types.GetRelationFactory
github.com/bangwork/bang-api/app/core/collector.AppendTeamUUIDAheadKey
github.com/bangwork/bang-api/app/core/scope.MustGetScopeByUUID
github.com/bangwork/bang-api/app/core/scope.CheckStatusExists
github.com/bangwork/bang-api/app/core/scope.CheckTaskFieldPermission
github.com/bangwork/bang-api/app/services/common.GetTransition
github.com/bangwork/bang-api/app/core/task/event.FireTaskCommentedEvent
github.com/bangwork/bang-api/app/models/commoncomment.ModelCommonComment
github.com/bangwork/bang-api/app/services/common/errors.IsMySQLRowDuplicateError
github.com/bangwork/bang-api/app/utils.IsUUID
github.com/bangwork/bang-api/app/core/user.MapTeamMemberUUID
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/core/task/internal/domain/relation/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.GetRelationValueUUIDs
github.com/bangwork/bang-api/app/core/sprint.MapByUUIDs
github.com/bangwork/bang-api/app/core/task/internal/domain/relation/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/internal/repo.MapFieldUUIDs
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldValueKey
github.com/bangwork/bang-api/app/core/task/internal/repo.UpdateStatusByTask
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldValueRepo
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewStringRelationValues
github.com/bangwork/bang-api/app/core/task/types.RelationValueToUUIDs
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/core/task/internal/domain.GetAllFieldTypes
github.com/bangwork/bang-api/app/core/task/utils.GetTaskDomains
github.com/bangwork/bang-api/app/models/issuetype/common.GetTeamDetailTypeMapFromCache
github.com/bangwork/bang-api/app/core/task/internal/repo.RealDeleteByTaskKeys
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldMultiValueRepo
github.com/bangwork/bang-api/app/core/task/internal/repo.MapFieldUUIDsByTask
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldValueKey
github.com/bangwork/bang-api/app/core/task/types.NewBaseRelationFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.GetRelationValueUUIDs
github.com/bangwork/bang-api/app/core/task/types.RelationValueToUUIDs
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/repo.BatchAddOrUpdateScriptFieldOptions
github.com/bangwork/bang-api/app/services/open-platform-services/field/script_field.SearchScriptFieldOption
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/utils.StringPtr
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewBaseProperty
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/utils.CoerceToString
github.com/bangwork/bang-api/app/utils.Md2Html
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/repo.AddOrUpdateFieldValues
github.com/bangwork/bang-api/app/core/task/internal/repo.GetFieldValue
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/utils.CoerceToString
github.com/bangwork/bang-api/app/utils.StringPtr
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/sprint.MapByUUIDs
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewBaseProperty
github.com/bangwork/bang-api/app/services/field.ErrorFieldByUUID
github.com/bangwork/bang-api/app/utils.CoerceToString
github.com/bangwork/bang-api/app/core/task/internal/repo.AddFieldMultiValues
github.com/bangwork/bang-api/app/core/task/internal/repo.DeleteByFieldValueKeys
github.com/bangwork/bang-api/app/core/task/internal/repo.RealDeleteByTaskKeys
github.com/bangwork/bang-api/app/core/task/internal/repo.MapFieldUUIDsByTask
github.com/bangwork/bang-api/app/core/task/internal/repo.NewFieldValueKey
github.com/bangwork/bang-api/app/core/task/internal/repo.GetByTaskFieldUUID
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/utils.InterfaceToStrings
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewFieldValuePropertyDriver
github.com/bangwork/bang-api/app/core/task/internal/domain/property/driver.NewTaskDriver
github.com/bangwork/bang-api/app/core/task/types.NewBasePropertyFromTaskKey
github.com/bangwork/bang-api/app/core/task/types.NewBaseProperty
github.com/bangwork/bang-api/app/core/task/internal/repo.MapFieldUUIDs
github.com/bangwork/bang-api/app/core/task/internal/repo.UpdateStatusByTask
github.com/bangwork/bang-api/app/utils.BuildArgs
github.com/bangwork/bang-api/app/core/task/internal/domain.BatchReadTaskDomainFromDB
github.com/bangwork/bang-api/app/core/task/internal/domain.NewReadOnlyTask
github.com/bangwork/bang-api/app/core/task/types.NewTaskKeys
github.com/bangwork/bang-api/app/utils/audit_log.SendTeamAuditLog
github.com/bangwork/bang-api/app/utils/user.GetBotUserByTeam'''
    a_array = []
    for line in a_str.split('\n'):
        if line.strip() == '':
            continue
        #     "github.com/bangwork/bang-api/app/utils/i18n.*": ["i18n", ""],
        # 把最后的函数换成 *, 再合回去
        line = line.strip()
        parts = line.split('.')
        parts[-1] = '*'
        line = '.'.join(parts)
        package = parts[1].split("/")[-1]
        a_array.append('"%s": ["%s", "%s"],' % (line, package, package))

    print('\n'.join(list(set(a_array))))



if __name__ == "__main__":
    # check_model_dir()
    # directory_module()
    function_call()
