import os.path
import subprocess

if __name__ == '__main__':
    files_path_map = [
        # 第3个不填就表示是新建的，大多数都是 bang-api 的
        (".github/workflows/create_release_arm64_version.yml", "bang-api-gomod",
         ".github/workflows/create_release_arm64_version.yml"),
        (".github/workflows/dev-ci.yml", "bang-api-gomod", ".github/workflows/dev-ci.yml"),
        (".github/workflows/inte-build.yml", "bang-api-gomod", ".github/workflows/inte-build.yml"),
        (".gitignore", "bang-api-gomod", ".gitignore"),
        ("README.md", "bang-api-gomod", "README.md"),
        ("app/controllers_refactor/task/types/types.go", "ones-project-api",
         "app/task/controllers_refactor/task/types/types.go"),
        ("app/core/task/internal/domain/property/desc_rich.go", "ones-project-api",
         "app/task/core/task/internal/domain/property/desc_rich.go"),
        ("app/init.go", "bang-api-gomod", "app/init.go"),
        ("app/models/field/field_group.go", "ones-project-api", "app/task/models/field/field_group.go"),
        ("app/models/field/field_relation.go", "ones-project-api", "app/task/models/field/field_relation.go"),
        ("app/models/layout/block.go", "ones-project-api", "app/task/models/layout/block.go"),
        ("app/models/layout/layout_third_tab_record.go", "ones-project-api",
         "app/task/models/layout/layout_third_tab_record.go"),
        ("app/models/manhour/manhour.go", "ones-api-biz-common", "foundation/manhour/models/manhour/manhour.go"),
        ("app/models/sso.v2/types.go", "bang-api-gomod", "app/models/sso.v2/types.go"),
        ("app/openapi/controllers/account/department/department.go", "bang-api-gomod",
         "app/openapi/controllers/account/department/department.go"),
        ("app/openapi/controllers/account/user/user.go", "bang-api-gomod",
         "app/openapi/controllers/account/user/user.go"),
        ("app/openapi/controllers/account/user/user_search.go", "bang-api-gomod",
         "app/openapi/controllers/account/user/user_search.go"),
        ("app/openapi/controllers/product/product.go", "bang-api-gomod", "app/openapi/controllers/product/product.go"),
        ("app/openapi/controllers/project/issue_field_group.go", "bang-api-gomod",
         "app/openapi/controllers/project/issue_field_group.go"),
        ("app/openapi/controllers/project/issue_worklog.go", "bang-api-gomod",
         "app/openapi/controllers/project/issue_worklog.go"),
        ("app/openapi/controllers/project/worklog.go", "bang-api-gomod", "app/openapi/controllers/project/worklog.go"),
        ("app/openapi/middlewares/guardian.go", "bang-api-gomod", "app/openapi/middlewares/guardian.go"),
        ("app/openapi/router/router.go", "bang-api-gomod", "app/openapi/router/router.go"),
        ("app/openapi/services/account/department/const.go", "bang-api-gomod",
         "app/openapi/services/account/department/const.go"),
        ("app/openapi/services/account/department/department.go", "bang-api-gomod",
         "app/openapi/services/account/department/department.go"),
        ("app/openapi/services/account/department/department_member.go", "bang-api-gomod",
         "app/openapi/services/account/department/department_member.go"),
        ("app/openapi/services/account/department/type.go", "bang-api-gomod",
         "app/openapi/services/account/department/type.go"),
        ("app/openapi/services/account/user/const.go", "bang-api-gomod", "app/openapi/services/account/user/const.go"),
        ("app/openapi/services/account/user/type.go", "bang-api-gomod", "app/openapi/services/account/user/type.go"),
        ("app/openapi/services/account/user/user.go", "bang-api-gomod", "app/openapi/services/account/user/user.go"),
        ("app/openapi/services/account/user/user_search.go", "bang-api-gomod",
         "app/openapi/services/account/user/user_search.go"),
        ("app/openapi/services/common/error_handler.go", "bang-api-gomod",
         "app/openapi/services/common/error_handler.go"),
        ("app/openapi/services/project/issue_field/issue_field.go", "bang-api-gomod",
         "app/openapi/services/project/issue_field/issue_field.go"),
        ("app/openapi/services/project/issue_worklog/simple/simple_issue_worklog.go", "bang-api-gomod",
         "app/openapi/services/project/issue_worklog/simple/simple_issue_worklog.go"),
        ("app/openapi/services/project/issue_worklog/summary/error.go", "bang-api-gomod",
         "app/openapi/services/project/issue_worklog/summary/error.go"),
        ("app/openapi/services/project/issue_worklog/summary/summary_issue_worklog.go", "bang-api-gomod",
         "app/openapi/services/project/issue_worklog/summary/summary_issue_worklog.go"),
        ("app/openapi/services/project/issue_worklog/summary/type.go", "bang-api-gomod",
         "app/openapi/services/project/issue_worklog/summary/type.go"),
        ("app/openapi/services/project/issue_worklog/utils.go", "bang-api-gomod",
         "app/openapi/services/project/issue_worklog/utils.go"),
        ("app/openapi/services/project/worklog/error.go", "bang-api-gomod",
         "app/openapi/services/project/worklog/error.go"),
        ("app/openapi/services/project/worklog/type.go", "bang-api-gomod",
         "app/openapi/services/project/worklog/type.go"),
        ("app/openapi/services/project/worklog/worklog.go", "bang-api-gomod",
         "app/openapi/services/project/worklog/worklog.go"),
        ("app/openapi/utils/date/date.go", "bang-api-gomod", "app/openapi/utils/date/date.go"),
        ("app/openapi/utils/graphql/batch_query.go", "bang-api-gomod", "app/openapi/utils/graphql/batch_query.go"),
        ("app/openapi/utils/graphql/simple_paging_query.go", "bang-api-gomod",
         "app/openapi/utils/graphql/simple_paging_query.go"),
        ("app/services/automation/runtime/teamhub.go", "bang-api-gomod", "app/services/automation/runtime/teamhub.go"),
        ("app/services/automation/types/formatter.go", "bang-api-gomod", "app/services/automation/types/formatter.go"),
        ("app/services/common/email/email.go", "bang-api-gomod", "app/services/common/email/email.go"),
        ("app/services/common/task/import_err_reason.go", "ones-project-api",
         "app/task/services/common/task/import_err_reason.go"),
        ("app/services/cron/email.go", "bang-api-gomod", "app/services/cron/email.go"),
        ("app/services/item/delegates/field_group.go", "bang-api-gomod", "app/services/item/delegates/field_group.go"),
        ("app/services/item/delegates/manhour.go", "bang-api-gomod", "app/services/item/delegates/manhour.go"),
        ("app/services/item/field/delegates/group_field.go", "bang-api-gomod",
         "app/services/item/field/delegates/group_field.go"),
        ("app/services/layout/block/base.go", "ones-project-api", "app/task/services/layout/block/base.go"),
        ("app/services/layout/block/init.go", "ones-project-api", "app/task/services/layout/block/init.go"),
        ("app/services/layout/block/tab.go", "ones-project-api", "app/task/services/layout/block/tab.go"),
        ("app/services/layout/block/task_entities.go", "ones-project-api",
         "app/task/services/layout/block/task_entities.go"),
        ("app/services/layout/block/task_fields_define.go", "ones-project-api",
         "app/task/services/layout/block/task_fields_define.go"),
        ("app/services/layout/custom_tab.go", "ones-project-api", "app/task/services/layout/custom_tab.go"),
        ("app/services/layout/delete.go", "ones-project-api", "app/task/services/layout/delete.go"),
        ("app/services/layout/init.go", "ones-project-api", "app/task/services/layout/init.go"),
        ("app/services/layout/issuetype/copy_dumpers.go", "ones-project-api",
         "app/task/services/layout/issuetype/copy_dumpers.go"),
        ("app/services/layout/issuetype/dumpers.go", "ones-project-api",
         "app/task/services/layout/issuetype/dumpers.go"),
        ("app/services/layout/issuetype/init.go", "ones-project-api", "app/task/services/layout/issuetype/init.go"),
        ("app/services/layout/issuetype/third_tab.go", "ones-project-api",
         "app/task/services/layout/issuetype/third_tab.go"),
        ("app/services/layout/schema.go", "ones-project-api", "app/task/services/layout/schema.go"),
        ("app/services/layout/schema/tabs.go", "ones-project-api", "app/task/services/layout/schema/tabs.go"),
        ("app/services/mail/batch.go", "bang-api-gomod", "app/services/mail/batch.go"),
        ("app/services/mail/email.go", "bang-api-gomod", "app/services/mail/email.go"),
        ("app/services/manhour/estimated_hour.go", "bang-api-gomod", "app/services/manhour/estimated_hour.go"),
        ("app/services/manhour/remaining_hour.go", "bang-api-gomod", "app/services/manhour/remaining_hour.go"),
        ("app/services/manhour/report/types.go", "bang-api-gomod", "app/services/manhour/report/types.go"),
        ("app/services/plugin-platform/abilities/implement/ability_init/ability_init.go", "bang-api-gomod",
         "app/services/plugin-platform/abilities/implement/ability_init/ability_init.go"),
        # ("app/services/plugin-platform/abilities/implement/layout_custom_issue_tab/layout_custom_issue_tab.go", "bang-api-gomod", "app/services/plugin-platform/abilities/implement/layout_custom_issue_tab/layout_custom_issue_tab.go"),
        (
        "app/services/project/delete_project.go", "ones-project-api", "app/project/services/project/delete_project.go"),
        ("app/services/resource/download.go", "bang-api-gomod", "app/services/resource/download.go"),
        ("app/services/sso.v2/dingding/api/api.go", "bang-api-gomod", "app/services/sso.v2/dingding/api/api.go"),
        ("app/services/sso.v2/dingding/api/types.go", "bang-api-gomod", "app/services/sso.v2/dingding/api/types.go"),
        ("app/services/sso.v2/dingding/api/util.go", "bang-api-gomod", "app/services/sso.v2/dingding/api/util.go"),
        ("app/services/task/form_import_customer.go", "ones-project-api",
         "app/task/services/task/form_import_customer.go"),
        ("db/bang.sql", "bang-api-gomod", "db/bang.sql"),
        ("devops/build.sh", "bang-api-gomod", "devops/build.sh"),
        ("devops/kubernetes/docker/Dockerfile", "bang-api-gomod", "devops/kubernetes/docker/Dockerfile"),
        # ("docs/account_docs.go", "bang-api-gomod", "docs/account_docs.go"),
        # ("docs/account_swagger.yaml", "bang-api-gomod", "docs/account_swagger.yaml"),
        # ("docs/admin_docs.go", "bang-api-gomod", "docs/admin_docs.go"),
        # ("docs/admin_swagger.yaml", "bang-api-gomod", "docs/admin_swagger.yaml"),
        # ("docs/auditlog_docs.go", "bang-api-gomod", "docs/auditlog_docs.go"),
        # ("docs/auditlog_swagger.yaml", "bang-api-gomod", "docs/auditlog_swagger.yaml"),
        # ("docs/automation_docs.go", "bang-api-gomod", "docs/automation_docs.go"),
        # ("docs/automation_swagger.yaml", "bang-api-gomod", "docs/automation_swagger.yaml"),
        # ("docs/copilot_docs.go", "bang-api-gomod", "docs/copilot_docs.go"),
        # ("docs/copilot_swagger.yaml", "bang-api-gomod", "docs/copilot_swagger.yaml"),
        # ("docs/department_docs.go", "bang-api-gomod", "docs/department_docs.go"),
        # ("docs/department_swagger.yaml", "bang-api-gomod", "docs/department_swagger.yaml"),
        # ("docs/desk_docs.go", "bang-api-gomod", "docs/desk_docs.go"),
        # ("docs/desk_swagger.yaml", "bang-api-gomod", "docs/desk_swagger.yaml"),
        # ("docs/devops_docs.go", "bang-api-gomod", "docs/devops_docs.go"),
        # ("docs/devops_swagger.yaml", "bang-api-gomod", "docs/devops_swagger.yaml"),
        # ("docs/file_docs.go", "bang-api-gomod", "docs/file_docs.go"),
        # ("docs/file_swagger.yaml", "bang-api-gomod", "docs/file_swagger.yaml"),
        # ("docs/importer_docs.go", "bang-api-gomod", "docs/importer_docs.go"),
        # ("docs/importer_swagger.yaml", "bang-api-gomod", "docs/importer_swagger.yaml"),
        # ("docs/issuetype_docs.go", "bang-api-gomod", "docs/issuetype_docs.go"),
        # ("docs/issuetype_swagger.yaml", "bang-api-gomod", "docs/issuetype_swagger.yaml"),
        # ("docs/item_docs.go", "bang-api-gomod", "docs/item_docs.go"),
        # ("docs/item_swagger.yaml", "bang-api-gomod", "docs/item_swagger.yaml"),
        # ("docs/license_docs.go", "bang-api-gomod", "docs/license_docs.go"),
        # ("docs/license_swagger.yaml", "bang-api-gomod", "docs/license_swagger.yaml"),
        # ("docs/message_docs.go", "bang-api-gomod", "docs/message_docs.go"),
        # ("docs/message_swagger.yaml", "bang-api-gomod", "docs/message_swagger.yaml"),
        # ("docs/notice_docs.go", "bang-api-gomod", "docs/notice_docs.go"),
        # ("docs/notice_swagger.yaml", "bang-api-gomod", "docs/notice_swagger.yaml"),
        # ("docs/org_config_docs.go", "bang-api-gomod", "docs/org_config_docs.go"),
        # ("docs/org_config_swagger.yaml", "bang-api-gomod", "docs/org_config_swagger.yaml"),
        # ("docs/organization_docs.go", "bang-api-gomod", "docs/organization_docs.go"),
        # ("docs/organization_swagger.yaml", "bang-api-gomod", "docs/organization_swagger.yaml"),
        # ("docs/resource_docs.go", "bang-api-gomod", "docs/resource_docs.go"),
        # ("docs/resource_swagger.yaml", "bang-api-gomod", "docs/resource_swagger.yaml"),
        # ("docs/role_docs.go", "bang-api-gomod", "docs/role_docs.go"),
        # ("docs/role_swagger.yaml", "bang-api-gomod", "docs/role_swagger.yaml"),
        # ("docs/task_swagger.yaml", "bang-api-gomod", "docs/task_swagger.yaml"),
        # ("docs/testcase_docs.go", "bang-api-gomod", "docs/testcase_docs.go"),
        # ("docs/testcase_swagger.yaml", "bang-api-gomod", "docs/testcase_swagger.yaml"),
        # ("docs/user_view_docs.go", "bang-api-gomod", "docs/user_view_docs.go"),
        # ("docs/user_view_swagger.yaml", "bang-api-gomod", "docs/user_view_swagger.yaml"),
        # ("docs/usergroup_docs.go", "bang-api-gomod", "docs/usergroup_docs.go"),
        # ("docs/usergroup_swagger.yaml", "bang-api-gomod", "docs/usergroup_swagger.yaml"),
        ("email_templates/add_related_tasks_html", "bang-api-gomod", "email_templates/add_related_tasks_html"),
        ("email_templates/batch_tasks_notice_html", "bang-api-gomod", "email_templates/batch_tasks_notice_html"),
        ("email_templates/batch_update_tasks_issue_notice_html", "bang-api-gomod",
         "email_templates/batch_update_tasks_issue_notice_html"),
        ("email_templates/cn/general_information/header_html", "bang-api-gomod",
         "email_templates/cn/general_information/header_html"),
        ("email_templates/cn/jira_migration/import_jira_fail_html", "bang-api-gomod",
         "email_templates/cn/jira_migration/import_jira_fail_html"),
        ("email_templates/cn/jira_migration/import_jira_success_html", "bang-api-gomod",
         "email_templates/cn/jira_migration/import_jira_success_html"),
        ("email_templates/cn/license_expired_html", "bang-api-gomod", "email_templates/cn/license_expired_html"),
        ("email_templates/cn/license_expiring_soon_html", "bang-api-gomod",
         "email_templates/cn/license_expiring_soon_html"),
        ("email_templates/cn/license_scale_changed_html", "bang-api-gomod",
         "email_templates/cn/license_scale_changed_html"),
        ("email_templates/cn/license_upgrade_html", "bang-api-gomod", "email_templates/cn/license_upgrade_html"),
        ("email_templates/com/change_password_html", "bang-api-gomod", "email_templates/com/change_password_html"),
        ("email_templates/com/free/com_free_upgrade_html", "bang-api-gomod",
         "email_templates/com/free/com_free_upgrade_html"),
        ("email_templates/com/free/com_free_welcome_html", "bang-api-gomod",
         "email_templates/com/free/com_free_welcome_html"),
        ("email_templates/com/general_information/footer_html", "bang-api-gomod",
         "email_templates/com/general_information/footer_html"),
        ("email_templates/com/general_information/header_html", "bang-api-gomod",
         "email_templates/com/general_information/header_html"),
        ("email_templates/com/jira_migration/import_jira_fail_html", "bang-api-gomod",
         "email_templates/com/jira_migration/import_jira_fail_html"),
        ("email_templates/com/jira_migration/import_jira_success_html", "bang-api-gomod",
         "email_templates/com/jira_migration/import_jira_success_html"),
        ("email_templates/com/trial/com_self_trial_expiration_html", "bang-api-gomod",
         "email_templates/com/trial/com_self_trial_expiration_html"),
        ("email_templates/com/trial/com_trial_expiration_html", "bang-api-gomod",
         "email_templates/com/trial/com_trial_expiration_html"),
        ("email_templates/com/trial/com_trial_feature_html", "bang-api-gomod",
         "email_templates/com/trial/com_trial_feature_html"),
        ("email_templates/com/trial/com_trial_questionnaire_html", "bang-api-gomod",
         "email_templates/com/trial/com_trial_questionnaire_html"),
        ("email_templates/com/trial/com_trial_welcome_html", "bang-api-gomod",
         "email_templates/com/trial/com_trial_welcome_html"),
        ("email_templates/copilot_embedding_result_html", "bang-api-gomod",
         "email_templates/copilot_embedding_result_html"),
        ("email_templates/free_org_expire_after_1_days_html", "bang-api-gomod",
         "email_templates/free_org_expire_after_1_days_html"),
        ("email_templates/free_org_expire_before_7_days_html", "bang-api-gomod",
         "email_templates/free_org_expire_before_7_days_html"),
        ("email_templates/general_information/header_html", "bang-api-gomod",
         "email_templates/general_information/header_html"),
        ("email_templates/import_jira_result_html", "bang-api-gomod", "email_templates/import_jira_result_html"),
        ("email_templates/invitation_free_html", "bang-api-gomod", "email_templates/invitation_free_html"),
        ("email_templates/invitation_html", "bang-api-gomod", "email_templates/invitation_html"),
        ("email_templates/license_expiring_soon_html", "bang-api-gomod", "email_templates/license_expiring_soon_html"),
        ("email_templates/license_scale_changed_html", "bang-api-gomod", "email_templates/license_scale_changed_html"),
        ("email_templates/license_upgrade_html", "bang-api-gomod", "email_templates/license_upgrade_html"),
        (
        "email_templates/password_expire_notice_html", "bang-api-gomod", "email_templates/password_expire_notice_html"),
        (
        "email_templates/related_objects_notice_html", "bang-api-gomod", "email_templates/related_objects_notice_html"),
        ("email_templates/request_create_team_code_html", "bang-api-gomod",
         "email_templates/request_create_team_code_html"),
        ("email_templates/reset_password_link_html", "bang-api-gomod", "email_templates/reset_password_link_html"),
        ("email_templates/single_operate_code_html", "bang-api-gomod", "email_templates/single_operate_code_html"),
        ("email_templates/sso_verify_html", "bang-api-gomod", "email_templates/sso_verify_html"),
        ("email_templates/task_activity_message/batch_merge_html", "bang-api-gomod",
         "email_templates/task_activity_message/batch_merge_html"),
        ("email_templates/task_comment_email_html", "bang-api-gomod", "email_templates/task_comment_email_html"),
        ("email_templates/task_deadline_email_html", "bang-api-gomod", "email_templates/task_deadline_email_html"),
        ("email_templates/task_notice_email_html", "bang-api-gomod", "email_templates/task_notice_email_html"),
        ("email_templates/task_update_email_html", "bang-api-gomod", "email_templates/task_update_email_html"),
        ("email_templates/wraps/task_wrap_html", "bang-api-gomod", "email_templates/wraps/task_wrap_html"),
        ("go.mod", "bang-api-gomod", "go.mod"),
        ("go.sum", "bang-api-gomod", "go.sum"),
        ("locales/i18n.json", "bang-api-gomod", "locales/i18n.json"),
        ("template/container/project-com.yaml", "ones-project-api", "app/project/services/project/project-com.yaml"),
        ("template/container/project.yaml", "ones-project-api", "app/project/services/project/project.yaml"),
        ("template/layout/validate_schema_0.json", "ones-project-api", "template/layout/validate_schema_0.json"),
        ("template/layout/validate_schema_3.json", "ones-project-api", "template/layout/validate_schema_3.json"),
        ("template/layout/validate_schema_9.json", "ones-project-api", "template/layout/validate_schema_9.json"),
    ]

    # docs/project_swagger.yaml
    # go.mod
    # go.sum
    # locales/i18n.json
    # migration/upgrade.yaml
    # template/component/sprint/v2.json
    # template/pandoc/custom-reference.docx

    bangwork_dir = '/Users/xhs/go/src/github.com/bangwork'
    old_project_path = '/Users/xhs/go/src/github.com/bangwork/bang-api-docker'
    have_not_deal_files = []
    for ft in files_path_map:
        f = ft[0]
        # 拼上新项目目录，看文件是否存在
        new_file = os.path.join(bangwork_dir, ft[1], ft[2])
        new_dir = os.path.dirname(new_file)
        if not os.path.exists(new_file):
            print(ft)
        if not os.path.exists(new_dir):
            os.makedirs(new_dir)
        # 文件存在，从旧项目目录拷贝到新项目目录
        old_file = os.path.join(old_project_path, f)
        # cp
        cp_cmd = f'cp {old_file} {new_file}'
        # 执行
        # move_result = subprocess.run(move_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        res = subprocess.run(cp_cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if res.returncode != 0:
            print(f'Error: {res.stderr.decode("utf-8")}')
